name: Run My Executable

on: [push, pull_request]  # Triggers the workflow on push or pull request

jobs:
  run-executable:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]  # You can add macOS as well if needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run window application on Windows
        if: runner.os == 'Windows'
        run: |
          ./Tutorial01_HelloTriangle.exe --mode d3d11_sw > output.txt 2>&1
          cat output.txt
      - name: Run console application on Windows
        if: runner.os == 'Windows'
        run: |
          ./BindingVariableParser.exe
      - name: Upload log as artifact
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: output.txt
